<!DOCTYPE html>
<html lang="pl">

    <head>
        <title></title>
        <meta charset="UTF-8" />
    </head>

    <body>
        
        <!-- komunikaty -->
        <?php
        /* @var $flashMessenger Zend_Controller_Action_Helper_FlashMessenger */
        $flashMessenger = Zend_Controller_Action_HelperBroker::getStaticHelper('flashMessenger');
        if ($flashMessenger->hasCurrentMessages()) {
            $message = $flashMessenger->getCurrentMessages();
            $flashMessenger->clearCurrentMessages();
        } else {
            $message = $flashMessenger->getMessages();
        }
        ?>
        <?php foreach ($message as $m): ?>
            <p style="color: red;">KOMUNIKAT: <?php echo $m ?></p>
        <?php endforeach ?>
        
        <!-- layout -->
        <?php echo $this->layout()->content; ?>

    </body>

</html>
